###############################################################
#
## Copyright (©) 2024-2025 David H Hoyt. All rights reserved.
##                 https://srd.cx
##
## Last Updated: 04-NOV-2025 1200Z by David Hoyt
#
#
#
#
# ADD LABEL File for Runners
#
#
#
#
#
#
#
#
###############################################################

Source:
  - '**/*.cpp'
  - '**/*.c'
  - '**/*.h'
  - '**/*.hpp'

Documentation:
  - '**/*.md'
  - 'docs/**'
  - 'README*'
  - 'CHANGELOG*'

configuration:
  - '**/*.json'
  - '**/*.yaml'
  - '**/*.yml'
  - '**/*.cmake'
  - '**/*.txt'

ci:
  - '.github/workflows/**'
  - '.github/**.yml'
  - '.github/**.yaml'

Testing:
  - 'Testing/**'

Tools:
  - 'Tools/**'

contrib:
  - 'contrib/**'

scripts:
  - 'tools/**'
  - 'scripts/**'
  - '**/*.py'

licenses:
  - 'LICENSE*'
  - 'COPYING*'
