name: XNU CodeQL

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write
  security-events: write

jobs:
  analyze:
    name: Analyze
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify Directory Structure
        run: |
          echo "Current directory:"
          pwd
          echo "Listing root directory:"
          ls -la
          echo "Listing DemoIccMAX directory:"
          ls -la .
      - name: Initialize the CodeQL tools
        uses: github/codeql-action/init@v4
        with:
          languages: cpp

      - name: Build with CMake
        run: |
          cmake -DCMAKE_INSTALL_PREFIX=$HOME/.local -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="-g -fsanitize=address,undefined -fno-omit-frame-pointer -Wall" -Wno-dev Build/Cmake/
          make clean
          make -j8
        working-directory: .

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v4
