###############################################################
#
## Copyright (©) 2024-2025 David H Hoyt LLC. All rights reserved.
##                 https://srd.cx
##
## Last Updated: 17-APRIL-2025 0800 EDT by David Hoyt (©)
#
## Intent: CICD-X7
#
## 
#
#
#
#
#
#
#
#
#
###############################################################

name: "CICD-X7"

on:
  workflow_dispatch:

jobs:
  build-linux:
    name: Build and Test Linux PR129 Branch
    runs-on: ubuntu-latest
    outputs:
      build-success: ${{ steps.check.outputs.success }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git anonymous identity
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libpng-dev libxml2 libxml2-dev libtiff-dev nlohmann-json3-dev build-essential \
            cmake clang clang-tools python3 python3-pip libwxgtk3.2-dev wx-common \
            libopencl-clang-17-dev curl git llvm clang-17 libjpeg-dev

      - name: Clone the PatchIccMAX repository
        run: |
          git clone https://github.com/xsscx/PatchIccMAX.git
          cd PatchIccMAX
          git checkout pr129

      - name: Configure the build with CMake
        run: |
          cd PatchIccMAX/Build
          export CC=gcc
          export CXX=g++
          export PATH="/usr/lib/llvm-17/bin:$PATH"
          echo "CC=gcc" >> $GITHUB_ENV
          echo "CXX=g++" >> $GITHUB_ENV
          clang++ --version
          clang --version
          cmake -DCMAKE_INSTALL_PREFIX="$HOME/.local" -DCMAKE_BUILD_TYPE=Debug \
                -DENABLE_TOOLS=ON -DENABLE_SHARED_LIBS=ON -DENABLE_STATIC_LIBS=ON \
                -DENABLE_TESTS=ON -DENABLE_INSTALL_RIM=ON -DENABLE_ICCXML=ON \
                -Wno-dev -DCMAKE_CXX_FLAGS="-g -fsanitize=address,undefined -fno-omit-frame-pointer -Wall" \
                -Wno-dev Cmake/

      - name: 🛠️ Build Project
        run: |
          cd PatchIccMAX/Build
          make -j$(nproc)
          find . -type f \( -perm -111 -o -name "*.a" -o -name "*.so" -o -name "*.dylib" \) -mmin -1440 ! -path "*/.git/*" ! -path "*/CMakeFiles/*" ! -name "*.sh" -print `` 
        continue-on-error: true

      - name: 📂 Prepare Testing Environment
        run: |
          cd PatchIccMAX/Testing/
          for d in ../Build/Tools/*; do
            [ -d "$d" ] && export PATH="$(realpath "$d"):$PATH"
          done

      - name: 🧪 Run CI Checks
        run: |
          cd PatchIccMAX/Testing
          curl -fsSL -o iccMAX-cicd-build-checks.sh https://raw.githubusercontent.com/xsscx/PatchIccMAX/refs/heads/pr128/contrib/UnitTest/iccMAX-cicd-build-checks.sh
          chmod +x iccMAX-cicd-build-checks.sh
          ./iccMAX-cicd-build-checks.sh 2>&1 | tee runner-output.log
        continue-on-error: true

      - name: 🧪 Run CalcTest Script
        run: |
          cd PatchIccMAX/Build
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/xsscx/PatchIccMAX/refs/heads/pr128/contrib/CalcTest/test_icc_apply_named_cmm.sh)"
        continue-on-error: true

      - name: ✅ Check build success
        id: check
        run: |
          if [ -f PatchIccMAX/Build/CMakeCache.txt ]; then
            echo "✅ Build configuration exists."
            echo "success=true" >> $GITHUB_OUTPUT
          else
            echo "❌ Build configuration failed."
            echo "success=false" >> $GITHUB_OUTPUT
            exit 1
          fi

      - name: 📦 Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: master-build-linux
          path: PatchIccMAX/Build

      - name: 🧾 Upload CI check logs
        uses: actions/upload-artifact@v4
        with:
          name: runner-output
          path: PatchIccMAX/Testing/runner-output.log
