###############################################################
#
## Copyright (©) 2024-2025 David H Hoyt. All rights reserved.
##                 https://srd.cx
##
## Last Updated: 23-OCT-2025 1200Z by David Hoyt
#
## Intent: Issue 188 Windows
#
## TODO: Add Unit Test Suite
#
#
#
#
#
#
#
#
#
###############################################################

name: Issue188-win
permissions:
  contents: read

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    strategy:
      matrix:
        build_type: [Release]

    steps:
      - uses: actions/checkout@v3

      - name: Cache vcpkg packages
        uses: actions/cache@v3
        with:
          path: |
            C:\vcpkg\installed
            C:\vcpkg\buildtrees
            C:\vcpkg\downloads
          key: vcpkg-${{ runner.os }}-${{ hashFiles('**/vcpkg.json') }}
          restore-keys: |
            vcpkg-${{ runner.os }}-
      - name: Cache build binaries
        uses: actions/cache@v3
        with:
          path: |
            DiccDEV\Build\Cmake\build
          key: cmake-build-${{ runner.os }}-${{ matrix.build_type }}-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            cmake-build-${{ runner.os }}-${{ matrix.build_type }}-
      - name: Build Issue 188
        run: |
          git clone https://github.com/ChrisCoxArt/iccDEV.git
          cd iccDEV
          git branch
          git status
          vcpkg integrate install
          vcpkg install
          cd Build\Cmake
          cmake -B build -S . -G "Visual Studio 17 2022" -A x64 ^
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} ^
          -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake
      - name: Build
        run: |
          cd iccDEV\Build\Cmake
          cmake --build build --config ${{ matrix.build_type }}
          dir /s /b *.exe *.lib
      - name: Run Unit Tests
        run: |
          cd iccDEV\Testing
          dir
          
