name: Passthru

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup vcpkg and clone DemoIccMAX repository
      run: |
              iex (iwr -Uri "https://raw.githubusercontent.com/xsscx/windows/refs/heads/main/pwsh/windev_troubleshooter.ps1").Content
