###############################################################
#
## Copyright (©) 2024-2025 David H Hoyt. All rights reserved.
##                 https://srd.cx
##
## Last Updated: 18-OCT-2025 1600Z by David Hoyt
#
## Intent: WinCmake for pr171
#
## TODO: Add Unit Test Suite
#
#
#
#
#
#
#
#
#
###############################################################

name: 23102005-002

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    strategy:
      matrix:
        build_type: [Debug]

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          git clone https://github.com/InternationalColorConsortium/iccDEV.git
          cd iccDEV
          git branch
          git status
          vcpkg integrate install
          vcpkg install
      - name: Configure
        run: |
          cd iccDEV
          cd Build\Cmake
          cmake -B build -S . -G "Visual Studio 17 2022" -A x64 ^
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} ^
          -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake
          cmake --build build --config ${{ matrix.build_type }}
