###############################################################
#
## Copyright (©) 2024-2025 David H Hoyt. All rights reserved.
##                 https://srd.cx
##
## Last Updated: 22-JULY-2025 0900 EDT by David Hoyt (©)
#
## Intent: WinArm2
#
## TODO: Sanitizer Builds
#
## Latest: Add create profiles and run tests
#          Add Windows PATH for Tools/ & Testing/
#
#
#
#
#
#
###############################################################

name: WinArm2

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-11-arm
    defaults:
      run:
        shell: cmd
    strategy:
      matrix:
        build_type: [Release]
    steps:
      - uses: actions/checkout@v3

      - name: Cache vcpkg packages
        uses: actions/cache@v3
        with:
          path: |
            C:\vcpkg\installed
            C:\vcpkg\buildtrees
            C:\vcpkg\downloads
          key: vcpkg-arm-${{ runner.os }}-${{ hashFiles('**/vcpkg.json') }}
          restore-keys: |
            vcpkg-${{ runner.os }}-
      - name: Cache build binaries
        uses: actions/cache@v3
        with:
          path: |
            PatchIccMAX\Build\Cmake\build
          key: cmake-arm-build-${{ runner.os }}-${{ matrix.build_type }}-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            cmake-build-${{ runner.os }}-${{ matrix.build_type }}-
      - name: Install dependencies
        run: |
          git clone https://github.com/xsscx/PatchIccMAX.git
          cd PatchIccMAX
          vcpkg integrate install
          vcpkg install
          vcpkg x-add-version --all
      - name: Configure
        run: |
          cd PatchIccMAX
          cmake -B build -S Build\Cmake -G "Visual Studio 17 2022" -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} "-DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake"
      - name: Build
        run: |
          cd PatchIccMAX\
          cmake --build build --config ${{ matrix.build_type }}
          dir /s /b *.exe *.lib
      - name: Update PATH for Tools
        run: |
             for /R PatchIccMAX\Tools %%D in (Debug) do (
             set "PATH=%%D;%PATH%"
             )
             echo Updated PATH: %PATH%
             cd PatchIccMAX\Testing
             .\CreateAllProfiles.bat
             .\RunTests.bat 
