name: WinSelfHost

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    env:
      BuildConfiguration: Debug
      BUILD_DIR: ${{ github.workspace }}/builds  # Ensure 'builds' directory exists

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup vcpkg and clone DemoIccMAX repository
      run: |
        $buildDir = "${{ env.BUILD_DIR }}"
        $vcpkgDir = "$env:RUNNER_TEMP/vcpkg"
        $outputDir = "$env:RUNNER_TEMP/output"
        # Create necessary directories
        New-Item -ItemType Directory -Path $buildDir -Force
        New-Item -ItemType Directory -Path $outputDir -Force
        # Check if vcpkg is installed
        if (Test-Path "$vcpkgDir\installed") {
            Write-Host "vcpkg is already installed. Continuing..."
        } else {
            Write-Host "vcpkg not found. Cloning and bootstrapping..."
            git clone https://github.com/microsoft/vcpkg.git $vcpkgDir
            cd $vcpkgDir
            .\bootstrap-vcpkg.bat
        }
        # Install libraries using vcpkg
        cd $vcpkgDir
        .\vcpkg.exe integrate install
        .\vcpkg.exe install egl-registry:x64-windows-static vcpkg-cmake:x64-windows-static vcpkg-cmake-config:x64-windows-static nlohmann-json:x64-windows nlohmann-json:x64-windows-static libxml2:x64-windows tiff:x64-windows wxwidgets:x64-windows libxml2:x64-windows tiff:x64-windows wxwidgets:x64-windows libxml2:x64-windows-static tiff:x64-windows-static wxwidgets:x64-windows-static --debug
        Write-Host "vcpkg libraries installed successfully"
        # Check if PatchIccMAX repository exists
        cd $buildDir
        if (Test-Path "$buildDir\PatchIccMAX") {
            Write-Host "PatchIccMAX repository already exists. Pulling latest changes..."
            cd "$buildDir\PatchIccMAX"
            git pull
        } else {
            Write-Host "Cloning PatchIccMAX repository..."
            git clone https://github.com/xsscx/PatchIccMAX.git PatchIccMAX
        }
        # Checkout development branch
        cd "$buildDir\PatchIccMAX"
        git checkout development
        Write-Host "DemoIccMAX repository checked out to development branch."
        # Verify directory structure
        if (-not (Test-Path "$buildDir\PatchIccMAX\Build\MSVC")) {
            Write-Error "Directory structure is not as expected: $buildDir\PatchIccMAX\Build\MSVC"
            Get-ChildItem -Path $buildDir\PatchIccMAX
            exit 1
        }
    - name: Find MSBuild Path using vswhere
      id: msbuild-locate
      run: |
        $vswherePath = "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe"
        $msbuildPath = & $vswherePath -latest -products * -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe
        if (-not $msbuildPath) {
          Write-Error "MSBuild.exe not found"
          exit 1
        } else {
          Write-Host "MSBuild found at: $msbuildPath"
        }
        echo "::set-output name=msbuild-path::$msbuildPath"
    - name: Verify solution file and build the project
      run: |
        $solutionPath = "${{ env.BUILD_DIR }}\PatchIccMAX\Build\MSVC\BuildAll_v22.sln"
        if (!(Test-Path $solutionPath)) {
            Write-Error "Solution file does not exist: $solutionPath"
            Get-ChildItem -Path "${{ env.BUILD_DIR }}\PatchIccMAX\Build\MSVC"
            exit 1
        } else {
            Write-Host "Solution file exists at: $solutionPath"
        }
        # Build the project using the dynamically located MSBuild
        $msbuildPath = "${{ steps.msbuild-locate.outputs['msbuild-path'] }}"
        $buildDir = "${{ env.BUILD_DIR }}\PatchIccMAX"
        cd $buildDir
        & $msbuildPath .\Build\MSVC\BuildAll_v22.sln `
            /m `
            /p:Configuration=Debug `
            /p:Platform=x64 `
            /p:AdditionalIncludeDirectories="$env:RUNNER_TEMP/vcpkg/installed/x64-windows/include" `
            /p:AdditionalLibraryDirectories="$env:RUNNER_TEMP/vcpkg/installed/x64-windows/lib" `
            /p:CLToolAdditionalOptions="/fsanitize=address /Zi /Od /DDEBUG /W4" `
            /p:LinkToolAdditionalOptions="/fsanitize=address /DEBUG /INCREMENTAL:NO"
    - name: Copy build artifacts to output directory
      run: |
        $directory = "${{ env.BUILD_DIR }}\PatchIccMAX"
        $outputDir = "$env:RUNNER_TEMP/output"
        $files = Get-ChildItem -Path $directory -Recurse -Include *.exe, *.dll, *.lib
        foreach ($file in $files) {
            Copy-Item -Path $file.FullName -Destination $outputDir
        }
    - name: List files in the output directory
      run: |
        Write-Host "Listing files in the output directory:"
        Get-ChildItem -Path "$env:RUNNER_TEMP/output"
    # Upload build artifacts
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: PatchIccMAX-Build-Artifacts
        path: $env:RUNNER_TEMP/output

    # Upload build logs (optional)
    - name: Upload build logs
      uses: actions/upload-artifact@v3
      with:
        name: PatchIccMAX-Build-Logs
        path: ${{ github.workspace }}/logs
