name: WinSelf

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup vcpkg and clone DemoIccMAX repository
      run: |
        iex (iwr -Uri "https://raw.githubusercontent.com/xsscx/PatchIccMAX/refs/heads/development/contrib/diag/windows_system_report.ps1").Content

    - name: Copy build artifacts to output directory
      run: |
        $directory = "${{ env.BUILD_DIR }}\PatchIccMAX"
        $outputDir = "$env:RUNNER_TEMP/output"
        $files = Get-ChildItem -Path $directory -Recurse -Include *.exe, *.dll, *.lib
        foreach ($file in $files) {
            Copy-Item -Path $file.FullName -Destination $outputDir
        }

    - name: List files in the output directory
      run: |
        Write-Host "Listing files in the output directory:"
        Get-ChildItem -Path "$env:RUNNER_TEMP/output"

    # Upload build artifacts
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: PatchIccMAX-Build-Artifacts
        path: $env:RUNNER_TEMP/output

    # Upload build logs (optional)
    - name: Upload build logs
      uses: actions/upload-artifact@v3
      with:
        name: PatchIccMAX-Build-Logs
        path: ${{ github.workspace }}/logs
